# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organiser_name', models.CharField(max_length=100)),
                ('lunch_name', models.CharField(max_length=100)),
                ('lunch_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('lunch_location', models.CharField(max_length=200)),
                ('menu_URL', models.CharField(max_length=200)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('starter', models.CharField(max_length=100)),
                ('main', models.CharField(max_length=100)),
                ('dessert', models.CharField(max_length=100)),
                ('drink', models.CharField(max_length=100)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='lunch',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrganiseLunch.Order'),
        ),
    ]
