# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrganiseLunch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lunch',
            new_name='Meal',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='lunch_datetime',
            new_name='meal_datetime',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='lunch_location',
            new_name='meal_location',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='lunch_name',
            new_name='meal_name',
        ),
    ]
