# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganiseLunch', '0002_auto_20170504_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='orders',
        ),
        migrations.AddField(
            model_name='meal',
            name='slack_channel',
            field=models.CharField(default='@lunchack', max_length=200),
            preserve_default=False,
        ),
    ]
